### ISSUE TITLE
Serde for RefArg

### ISSUE THREAD

**Issue by benjumanji** [diwic/dbus-rs#267] opened 2020-05-22 10:26 UTC
I'm dropping this idea here, I don't have time to work on it _right now_ but maybe in a few months. I'm cobbling together a bunch of dbus client code for various dbus exposed networking services, and for the most part it's pretty pleasant. Great work! The codegen is a godsend. The ugliest part of it right now without a doubt is marshaling. It occurs to me that a serde_dbus crate would cut down on so much boilerplate. I'm crunching rn so I can't justify it but when I get some breathing room hopefully I'll be back.

**Comment by diwic** [comment] 2020-05-22 15:52
Last time I looked - three years ago - serde had problems with correct type on empty arrays, see https://github.com/diwic/dbus-rs/issues/56 
Do you know if that has improved since?

**Comment by diwic** [comment] 2020-05-22 15:55
Also, could you elaborate on where you find things to be ugly? With latest enhancement or `AppendAll` and `ReadAll` traits, I find things quite ergonomic.

**Comment by benjumanji** [comment] 2020-05-23 12:54
Sure: it's also possible that I am getting things completely wrong with the current api. Given something like `HashMap<String, Variant<Box<dyn RefArg>>>` I'm not sure how to say get the key "KeyMgmt" and decode it as an array of strings in a nice way. Currently I'm using `.as_iter()`, pulling on it once to get the array element, using `as_iter()` again, then tugging on that to get my string keys, but I also need to cast all of them as well.

I'll have a look at #56. Maybe it's still unsolved.

**Comment by diwic** [comment] 2020-05-23 13:09
Ah, right. So `RefArg` is meant to be an escape hatch when the `Append`/`Read` stuff cannot work. 
But you're right, there could be more ergonomic ways to drag the information out of the refarg.

You can probably use `.0` to descend into the Variant instead of using `as_iter`, that might help with one of the steps.

**Comment by diwic** [comment] 2020-05-25 13:15
Actually, as of dbus 0.8.3 we commit to arrays of strings being `Vec<String>` so you should be able to cast directly to that, i e,

    let value: &Vec<String> = dbus::arg::cast(map.get("KeyMgmt")?.0)?;

That does not look too bad. Does it work for you?

**Comment by benjumanji** [comment] 2020-05-28 12:47
I can try that, thanks!

**Comment by benjumanji** [comment] 2020-05-28 13:24
It's definitely better. I still think I'd like to have a go at something that generates accessors a la serde, but this is certainly _much_ better than what I had before, thanks!

**Comment by paulvt** [comment] 2020-08-17 07:57
I have also been struggling to serialize data from a property/method result into JSON.
For example, if you have something like `a{sv}` the result is `HashMap<String, Variant<dyn Box<RefArg>>>` .
I'm writing a helper function that turns the variants into a JSON value, but because `as_iter()` does not yield an array of dict entries of the key/value pair, but just an array of key/values, the serializer cannot know it is a map instead of a list?

Example match:
```rust
    match val.arg_type() {
        ArgType::Array => {
            let iter = val.as_iter().unwrap();
            let vec = iter.map(|item| json_value(item)).collect::<Vec<_>>();
            // FIXME: Handle the case when it is an array of dict entries but there is no way to find out what the inner type is?
            json!(vec)
        }
        ArgType::Variant => {
            // Suggest was to use val.0, this doesn't work?
            let mut iter = val.as_iter().unwrap();
            let v_inner = iter.next().unwrap();
            json_value(v_inner)
        }
        ArgType::Boolean => {
            // ...
        }
        ArgType::Invalid => unreachable!("Cannot handle invalid arguments"),
        ArgType::String | ArgType::ObjectPath | ArgType::Signature => json!(val.as_str().unwrap()),
        ArgType::DictEntry => {
            // Somehow this is never returned?
        }
        ArgType::Byte | ArgType::UInt16 | ArgType::UInt32 | ArgType::UInt64 | ArgType::UnixFd => {
            json!(val.as_u64().unwrap())
        }
        ArgType::Int16 | ArgType::Int32 | ArgType::Int64 => json!(val.as_i64().unwrap()),
        ArgType::Double => json!(val.as_f64().unwrap()),
        ArgType::Struct => {
          // Somehow this is never returned?
        }
    }
```

So the problem is that one needs to be able to peek inside to find out the proper inner type and that the `Struct` and `DictEntry` variants are never produced.

**Comment by diwic** [comment] 2020-08-25 17:45
@paulvt This sounds like a separate issue, but anyhow: for the dicts, would it work to use `val.signature()`? Dict signatures start with `a{` whereas normal arrays have some other second letter. Structs should start with signature `(` but it seems like a bug if `ArgType::Struct` is not returned...

**Comment by paulvt** [comment] 2020-09-07 14:47
Even it it were to work for arrays of structs, I fail to see the difference between `a{sv}` and `a(sv)`?
I could look at `val.signature()` but then I kind of start to parse those signature strings myself, which feels weird.
However, I can use it as a workaround, I guess.

**Comment by diwic** [comment] 2020-09-08 08:44
@paulvt If you have time, could you provide a test case where you expect ArgType::Struct to be returned but it is not? And open a separate bug for that issue? If so I'll look into it.

@benjumanji I have recently added a new function `dbus::arg::prop_cast` (in git master) which might help with getting a value out of a `HashMap<String, Variant<Box<RefArg>>>`. Could you have a look?

**Comment by benjumanji** [comment] 2020-09-12 20:21
@diwic yeah, I'll try to get a look in this coming week.

**Comment by diwic** [comment] 2020-09-18 12:37
@paulvt I have just released v0.9 of dbus, and there are some changes to RefArg which just might help with the struct argtype not being returned. Could you verify?

**Comment by paulvt** [comment] 2020-10-29 15:30
@diwic Finally got around to checking that struct works. But unfortunately dict entry does not.
While with debug printing I see that there is an `InternalDict` so the lower structure is aware that it is a dict. So, I wonder why iterator cannot yield dict entries whose iterator in turn return `s`, `v`, like `a(ssu)` would yield structs of `(ssu)` whose iterator would return `s`, `s`, `u`.

**Comment by diwic** [comment] 2020-10-30 10:38
@paulvt Good, this is expected.

The reason it can't/shouldn't work with dict entries, is because dict entries cannot exist outside arrays, this would be a violation of the D-Bus spec. Therefore I have decided that it makes more sense conceptually to not be able to have RefArgs that are dict entries. I suspect this makes some other code easier and more ergonomic to write as well. 

So for figuring out the difference between a dict, and an array of something else than a dict entry, you need to look at the second character of the RefArg's signature, just looking at the ArgType is not enough.

**Comment by diwic** [comment] 2021-01-16 11:23
We currently have `dbus::arg::prop_cast` and also a recently committed codegen that uses this to have type-safe bindings to properties (see the `--prop-newtype` option). 

I believe this is a suitable replacement for "Serde for RefArg" - and nobody seems willing to work on the Serde part anyway - so I'm going to close this one. Feel free to reopen in case I misunderstood something or circumstances change. Thanks!

**Closed by diwic** 2021-01-16 11:23 UTC
Labels: enhancement
