### ISSUE TITLE
"reenable" rustfmt

### ISSUE THREAD

**Issue by hellow554** [diwic/dbus-rs#382] opened 2022-04-19 14:24 UTC
There is is comment `"Please don't run rustfmt on this repository" = true` with an issue linked to https://github.com/rust-lang/rustfmt/issues/3745

Honestly: I would have rather "imperfect" formatting, than no formatting at all. IMHO it's not very readable in the current situation, e.g. `while`s and `if`s are on one line.

Please concider bringing it back and do a format on the whole tree: 
```
cargo fmt && git diff --shortstat

 82 files changed, 6106 insertions(+), 3546 deletions(-)
```

**Comment by diwic** [comment] 2022-04-19 17:41
This is a duplicate of #191, the reasons for not enabling rustfmt are explained there.

**Closed by diwic** 2022-04-19 17:41 UTC
