### ISSUE TITLE
dbus-rs set a illegal signature 'r'

### ISSUE THREAD

**Issue by poxar** [diwic/dbus-rs#24] opened 2015-09-29 15:25 UTC
When sending a `struct` in an `array` like this

```rust
extern crate dbus;
use dbus::{Connection, BusType, MessageItem, Message};

fn main() {
    let c = Connection::get_private(BusType::Session).unwrap();
    let mut m = Message::new_method_call("org.test.rust",
                                        "/", "org.test.rust",
                                        "Test").unwrap();

    let a = MessageItem::from("test".to_string());
    let b = MessageItem::from("test".to_string());
    let foo = MessageItem::Struct(vec!(a, b));
    let bar = foo.clone();

    let args = [MessageItem::new_array(vec!(foo, bar)).unwrap()];
    println!("{:?}", args);

    m.append_items(&args);
    c.send(m).unwrap();
}
```

The signature is set to "r", which, according to the D-Bus documentation, "is reserved for use in bindings and implementations to represent the general concept of a struct, and must not appear in signatures used on D-Bus".

Trying to send such a Message results in

```
arguments to dbus_message_iter_open_container() were incorrect, assertion "(type == DBUS_TYPE_ARRAY && contained_signature && *contained_signature == DBUS_DICT_ENTRY_BEGIN_CHAR) || (contained_signature == NULL || _dbus_check_is_valid_signature (contained_signature))" failed in file dbus-message.c line 2914.
```

This could or could not be a bug in the dbus library according to [this](1) and [this](2).

Anyways manually setting the signature works around the issue:

```rust
extern crate dbus;
use dbus::{Connection, BusType, MessageItem, Message};
use std::borrow::Cow;

fn main() {
    let c = Connection::get_private(BusType::Session).unwrap();
    let mut m = Message::new_method_call("org.test.rust",
                                        "/", "org.test.rust",
                                        "Test").unwrap();

    let a = MessageItem::from("test".to_string());
    let b = MessageItem::from("test".to_string());
    let foo = MessageItem::Struct(vec!(a, b));
    let bar = foo.clone();

    let args = [MessageItem::Array(vec!(foo, bar), Cow::Owned("(ss)".to_string()))];

    m.append_items(&args);
    c.send(m).unwrap();
}
```

[1]: https://bugs.launchpad.net/ubuntu/+source/dbus-c++/+bug/1098723
[2]: https://chromium.googlesource.com/chromiumos/third_party/dbus-cplusplus/+/32fe2ce6a60f6f9e5771c639598050798a4feae8

**Comment by diwic** [comment] 2015-09-29 19:29
Thanks for your bug report! I believe the issue is now fixed in the commit referenced above, and I also took the liberty of adding your code above as a new test case.

**Closed by diwic** 2015-09-29 19:29 UTC

**Comment by poxar** [comment] 2015-09-30 08:20
Cool, that was fast. :) It fixes the issue both in my testing and production code. Thanks!
