### ISSUE TITLE
memory usage with large numbers of objects

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#47] opened 2016-07-13 15:35 UTC
Hi, my friend @tasleson did some work to find out the memory usage of using dbus, and saw high memory usage by dbus-rs, worse than when implemented in Python. His code is here:

https://github.com/tasleson/misc-tools/tree/master/dbus_memory/rust

My theory is this is because dbus-rs is not sharing identical strings, such as interface or property names, that sort of thing, which adds up when there are large numbers of each, but this is just a guess at the moment.

**Comment by diwic** [comment] 2016-07-13 17:18
I clone strings *a lot*, (look at all the `ArcMap`s in the code), so that shouldn't be it.

**Comment by tasleson** [comment] 2016-07-13 17:22
My theory was because each and every dbus object has multiple hash maps, but that's just a guess.

**Comment by diwic** [comment] 2016-07-13 17:43
I wonder how much of this is jemalloc's fault. Want to give it a try with alloc_system and see if it helps?

What you add a lot of here are properties, and a property looks like this:

    pub struct Property<M> {
        name: Arc<String>,
        value: Mutex<MessageItem>,
        emits: EmitsChangedSignal,
        rw: Access,
        set_cb: Option<M>,
        owner: Mutex<Option<(Arc<Path<'static>>, Arc<IfaceName<'static>>)>>,
        anns: BTreeMap<String, String>,
    }

Which is 176 bytes directly, not counting strings etc.

**Comment by tasleson** [comment] 2016-07-14 00:51
Running rust, rustc 1.12.0-nightly (7ad125c4e 2016-07-11):
```
307840 KB  alloc_system
357172 KB  default
```
An improvement, but still quite a bit of memory.

`Note: memory is Resident Memory Size (KiB) as displayed from top.`

**Comment by diwic** [comment] 2016-07-14 05:24
300 MB for ~10000 properties? Yikes.

**Comment by diwic** [comment] 2016-07-14 18:03
I can't reproduce here. Here's what I get:
 >     VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 >    53756  21912   2728 S   0,0  0,6   0:00.01 dbus_test 

I can't say 22 MB is tiny, but it's an order of magnitude better than the 300 MB you're getting. 

This is running under Ubuntu 16.04 and rustc 1.10.0-nightly (179539f6e 2016-05-20)

**Comment by tasleson** [comment] 2016-07-14 18:12
@diwic  Wow!  I did my test in Fedora 24, this result is encouraging.

**Comment by diwic** [comment] 2016-07-14 18:28
Just tried upgrading to `rustc 1.12.0-nightly (7ad125c4e 2016-07-11)` - no significant in memory usage compared to 1.10.

**Comment by tasleson** [comment] 2016-07-15 02:40
I spun up a xubuntu 16.04 VM and I'm see the same large memory consumption with `rustc 1.12.0-nightly (7ad125c4e 2016-07-11)` .  I'm doing `cargo run --release` not sure what I'm doing different.

**Comment by diwic** [comment] 2016-07-15 07:54
@tasleson  Wild guess, but you haven't made any changes to your repo that you forgot to push? Last commit is from May.

**Comment by tasleson** [comment] 2016-07-18 16:43
@diwic You are 100% correct, I had uncommitted changes in my directory.  I committed and pushed.  Your test had 604 dbus objects instead of the 10K I had.

**Comment by tasleson** [comment] 2016-07-18 17:11
@diwic With the correct number of objects (10K) you should see similar memory consumption.  Our main concern is that it takes 300+ MB memory to serve up ~5 MB of data to the client.
```
./dbus_size.py session com.blah.storage /com/blah/storage/block
{   'booleans': 49995,
    'byte_count': 0,
    'dbus_object_num': 10000,
    'dictionary_key_num': 0,
    'dictionary_key_size_total': 0,
    'double_count': 0,
    'int32_count': 0,
    'int64_count': 0,
    'interface_num': 30000,
    'interface_size_total': 939999,
    'object_path_num': 10000,
    'object_path_size_total': 278885,
    'property_name_num': 199980,
    'property_name_size_total': 1429857,
    'string_num': 89991,
    'string_size_total': 1648725,
    'uint32_count': 9999,
    'uint64_count': 49995}
We retrieved 10000 objects
Size fixed len data = 489951
Size variable len data (strings) = 4297466
Total bytes 4787417
Average bytes per object 478
```

**Comment by tasleson** [comment] 2016-07-18 19:23
Tried using the https://github.com/gperftools/gperftools tools, generated this output ([rust_mem.pdf](https://github.com/diwic/dbus-rs/files/369916/rust_mem.pdf)) which doesn't appear super useful.  The MB amounts are zero, but the percentages look interesting.  I think it has potential if it worked better.  I'm likely doing something wrong.  I used http://stackoverflow.com/questions/38254937/how-do-i-debug-a-memory-issue-in-rust for suggestions.

**Comment by diwic** [comment] 2016-07-19 04:17
Ok. I did some profiling based on your test and came up with one low-hanging fruit of not allocating unnecessary `BTreeMap`s when there are no annotations (apparently BTreeMap itself does not optimise for the empty case, like Vec does). It's now pushed to master.

For me, this cuts the memory usage in half, approximately. 

Other than that, I'm not sure - 150 MB means 750 bytes per property and a lot of that is pointers/usizes (e g, an `Arc<String>` is 40 bytes, four usizes and a pointer), so moving to 32 bit code would save a significant amount.

**Comment by diwic** [comment] 2016-07-19 04:31
JFTR, the profiling was done with [valgrind/massif](http://valgrind.org/docs/manual/ms-manual.html) after switching dbus_test over to alloc_system.

**Comment by diwic** [comment] 2016-07-19 17:08
I've been thinking about this today and I think it would be possible to rewrite the Tree stuff a bit so that it would be possible to use the same `Interface` struct for many `ObjectPath`s. For the test case that would work fine and likely save a lot of memory. Calls to `on_set` (and `on_get` would be added), would then have to check what object path they're on in order to get/set the right object. Would that make sense in a real-world scenario too?

**Comment by tasleson** [comment] 2016-07-19 17:37
@diwic I'm a little confused by the wording here.  Do you mean to say same interface struct for objects that implement the same interface instead of for many object paths?  The example is kind of arbitrary.  In real world we would have dbus objects which have one or more interfaces that are dynamically added to and removed based on change in object.

**Comment by diwic** [comment] 2016-07-19 18:06
@tasleson 
> I'm a little confused by the wording here.

Sorry. English is not my native language so it's hard to find the right words sometimes.

>  Do you mean to say same interface struct for objects that implement the same interface instead of for many object paths?

Yes. In your example, you would create the `com.blah.storage.BlockDevice` interface only once, then add a clone (which just increases the Arc refcount) of that interface to the 10K object paths.

 >  In real world we would have dbus objects which have one or more interfaces that are dynamically added to and removed based on change in object.

That's fine (although we don't have any `InterfacesAdded` support in GetObjectManager yet). As long as it's not 10K *different* interfaces.

**Comment by tasleson** [comment] 2016-07-19 18:37
@diwic The total number of different interfaces would certainly not be 10K.  However, it could be in the 40-50 range with no specific object having more than 4-5.  We are talking about a fairly large dbus service in terms of functionality and in terms of number of objects served.

Thanks for digging into all of this, it's encouraging and makes it more reasonable that rust is a viable language choice.

**Comment by tasleson** [comment] 2016-07-19 22:05
@diwic Thanks for the tip on getting memory information better.  I compiled with the system allocator and I'm seeing better results with gperf, however interpreting the results is not blatantly obvious to me at the moment.
[dbus_test_mem.pdf](https://github.com/diwic/dbus-rs/files/372525/dbus_test_mem.pdf)

**Comment by diwic** [comment] 2016-07-20 19:58
> Thanks for digging into all of this, it's encouraging and makes it more possible that rust is a viable language choice.

Well, makes me more motivated to work on things if I know they'll be used. :-) I started writing some code today to decouple the property from the value it currently contains (and try to solve https://github.com/diwic/dbus-rs/issues/39 in the process, if possible) but it needs some rewriting and rethinking...

**Comment by diwic** [comment] 2016-07-31 15:45
Hi, my new tree module is shaping up to the point that I can make dbus_test work with it. The modified code is [here](https://github.com/diwic/misc-tools). It takes 12 MB to serve the data that took 300 MB before.

Give it a try and see if you can replicate my results and if the new code is working the way you expect. Thanks!

**Comment by tasleson** [comment] 2016-08-01 15:14
@diwic This is excellent progress, thanks!  I will take a peek at all of this as soon as I can!

**Comment by diwic** [comment] 2016-09-03 18:25
Apparently a month has gone and nothing happened on your side, so I'm releasing v0.4.0 anyhow. I hope it fixes your issue. Also have a look at the new `adv_server.rs` example which includes some ideas on how to make use of the new tree module. Enjoy!

**Closed by diwic** 2016-09-03 18:25 UTC

**Comment by tasleson** [comment] 2016-09-03 23:36
@diwic Sorry, will spend some time looking at this in the next week!

**Comment by tasleson** [comment] 2016-09-22 17:20
@diwic Tried out your changes and the memory improvement is impressive, thank you!
