### ISSUE TITLE
Exposed File Descriptors

### ISSUE THREAD

**Issue by yodaldevoid** [diwic/dbus-rs#81] opened 2017-03-30 17:29 UTC
Is there a reason why the API requires the user to work with "raw" file descriptors? Has any thought been put into an API that does not expose the implementation details to the programmer, possibly using `futures`? I am asking as the current async API rubs me the wrong way from a typical Rust API point of view. I wanted to learn if any thought had been put into this before I go off and try to implement it myself.

**Comment by diwic** [comment] 2017-03-30 18:22
I've given it quite some thought and started writing some draft code, but honestly I have not got very far. 

Another risk is that tokio is quite new and I'm not sure of how stable the API will be towards people wanting to provide their own Fds. 

But this looks like a duplicate of https://github.com/diwic/dbus-rs/issues/72 - if you have deep insight in how tokio works (because, believe me, that's needed for writing something like this) would you mind continue discussing there and providing some guidance on how the integration should best be done?

**Comment by diwic** [comment] 2017-03-30 18:22
Closing due to duplicate of https://github.com/diwic/dbus-rs/issues/72

**Closed by diwic** 2017-03-30 18:22 UTC
